### ISSUE TITLE
int object is not iterable

### ISSUE THREAD

**Issue by Guigui220D** [robhagemans/monobit#11]
Trying to convert from a png image, I installed pillow. Running with latest python3, i get this error:
![image](https://user-images.githubusercontent.com/24529384/192363577-f8293b61-e5a6-4583-b089-736e8248527d.png)

**Comment by Guigui220D** [comment]
![image](https://user-images.githubusercontent.com/24529384/192363701-468535e0-b2dc-4c72-b4e5-050d9ab4ccfb.png)

here is the debug log

**Comment by robhagemans** [comment]
Thanks, what's happening there is that it assumes the PNG has colours in
RGB format. Will be fixed in some later version. For now you could convert
the PNG to use RGB colours and run through monobit

**Comment by Guigui220D** [comment]
Aah
iirc this picture had 1bpp which i thought was the good thing to do for a bitmap font
Thanks!

**Comment by robhagemans** [comment]
Fixed with 738953c
