### ISSUE TITLE
Expected container format, got non container stream

### ISSUE THREAD

**Issue by Guigui220D** [robhagemans/monobit#12]
![image](https://user-images.githubusercontent.com/24529384/192477807-6967c854-feee-41eb-9be8-74e23f7888b3.png)

I'm getting the error above when trying to convert from png to draw

**Comment by robhagemans** [comment]
Bug fixed by d595a5c. Please note though that you'll need to define an encoding for your image if you want to save as .draw, as that format can only store glyphs with Unicode labels.

**Comment by Guigui220D** [comment]
@robhagemans how would i go about doing that? through the command line options? I can't find how to use --encoding option
