### ISSUE TITLE
propose to use unicode SQUARE 

### ISSUE THREAD

**Issue by wtjcn** [robhagemans/monobit#15]
propose to use unicode SQUARE to display, maybe a new format name
U+25A0 | BLACK SQUARE (U+25A0) | ■ |
U+25A1 | WHITE SQUARE (U+25A1) | □ |

use ultraedit with Fixedsys font show this:

![2023-02-06 090847](https://user-images.githubusercontent.com/1143890/216859515-2fcecb85-18a8-44db-ae2a-d8ea3b9c6c08.png)

**Comment by robhagemans** [comment]
Hi, you can render output (e.g. though `monobit-banner`) with any character you like, including squares. As too the `yaff` format, I'm not going to fundamentally change that now. An important reason for using ASCII for the glyph definitions and metrics is that it makes the format easily understood irrespective of people's locale settings or choice of editor or font.

As to defining another additional format to support this, I think I've done enough damage already by defining one...
