### ISSUE TITLE
Dashen fonts

### ISSUE THREAD

**Issue by dyacob** [robhagemans/monobit#18]
Greetings, I was elated to find this project -it would have saved me **huge** amounts of time back in '95 - '98.  I'm hoping `monobit` can help me migrate some fonts forward.  Trying `monobit-convert load` out with some `pft` files I see output like the following, where I'm wondering if the `right-bearing` info is just a warning or a fatal error?

```
name: ^Q
spacing: proportional
bounding-box: 0 0
font-id: ^Q
converter: monobit v0.36
source-name: amdl1103.pft
source-format: ChiWriter (0x0)
history: load -format=pcpaint
shift-up: 255

0x20:
    -

    right-bearing: 37


0x011f:
    -

    right-bearing: 8


0x0120:
    -

    right-bearing: 37

   ⋮
```

`monobit-convert` will produce a `.png` file, but the visual result is not intelligible to me.  Trying BDF output gets the following error consistently:

```
ERROR: BDF default glyph must have a character or codepoint.
ERROR: integer division or modulo by zero
```
GitHub isn't allowing me to attach the `pft` files to help with investigation, so I've added them to a G-Drive folder here.  Note that these are non-Roman fonts, they have Ethiopic glyphs:

https://drive.google.com/drive/folders/1Ttg30yOE6kAYosndFpHMrjm-Z6zKbNOq?usp=share_link

thanks!

**Comment by robhagemans** [comment]
Hi Daniel, I can have a look - it'll be an interesting test file as so far
the vast majority of files I worked with have been Western scripts.

However do you have any background to the font file, for example what
program it was used with? It seems monobit is trying to interpret them as
ChiWriter/GRASP/PC-Paint files but is not extracting them successfully (all
glyphs come out empty). That may be a bug, but it may also be the case that
the file format is something else than it thinks.

Thanks
Rob

**Comment by dyacob** [comment]
Hi Rob, thanks much for taking a look. 

The fonts were used with a DOS Amharic editor application named "Dashen", which may have been an extension of ChiWriter.  I had the impression that the fonts were in a standard format that printers of the day would understand.  I'll ask the author if the fonts are ChiWriter compatible or something proprietary. It may take a few days to get a response.

**Comment by robhagemans** [comment]
Thanks!

I had a (very quick) look at the file and I don't think it's closely
related to ChiWriter. However it looks like the glyphs are stored fairly
straightforwardly. Especially if you are in contact with the author and/or
have some documentation of the file format, it should not be too difficult
to add a converter for it.

I don't know if the original program and the fonts are still of commercial
interest to the author, but they may well be willing to help out with some
technical documentation...

**Comment by robhagemans** [comment]
I had a slightly closer look at one file, `amds1103.pft`. It looks like this file has two parts, a screen font followed by a printer font starting at offset 3680. 

The printer font part is a straightforward PCL bitmap soft font (documented at https://developers.hp.com/hp-printer-command-languages-pcl/doc/pcl-implementors-guide-archived-1995) - not yet supported by monobit but can be done.

The screen font before that is perhaps a format specific to Dashen - 
- offset 0: 18 bytes of unknown data
- offset 18: a table with 32-bit little-endian values denoting bytes offsets into the glyph data
- offset 1038: 32 bytes of unknown data
- offset 1070: glyph data. I think the bitmaps are stored in transposed form, with each byte denoting an 8-pixel column. In that case, the glyph record looks like this: 3-byte header (1-byte width, 1-byte, maybe a vertical offset, 1-byte height) followed by variable-length glyph data. If the height is 8 or less (which was true for all glyphs in this file) the length of the glyph data in bytes equals the glyph width. 
-  offset 3424: probably an encoding table denoting the byte character associated with each glyph. TBD which encoding.

With your knowledge of the Ethiopic script and encodings and my guesswork above we can probably do a decent job extracting the font data, and maybe find out a bit more about what the unknown data means. However with some original documentation everything would be a lot easier :)

**Comment by dyacob** [comment]
Two fonts in one, well that's a bit clever. Also impressive that you could decode what was going on!  So it seems like a good opportunity to incorporate PCL into monobit, I can certainly help by validating the glyphs.  On the encoding, I think it would most certainly be a single-byte encoding.  Unicode for Ethiopic didn't arrive until late 1999.

**Comment by robhagemans** [comment]
Hi yes, a table mapping the positions to Unicode is exactly what's needed. Fair enough that it'll be vendor-dependent, but after all so its the font format to begin with so if we have one we might as well have the other. I've got dozens of encoding tables included,  it's not a big deal to include another one...

I'm not sure I understand you correctly by a mapping to ANSI address, do you mean mapping these to the high 128 positions in an 8-bit mapping, with ASCII glyphs in the lower 128? I guess that's how it would be mapped in DOS, but these fonts appear to use almost the full 256 positions for Ethiopic glyphs. It would be needed to convert text files from that time, but to decode the fonts the Unicode mapping would be more relevant.

**Comment by dyacob** [comment]
Hi, I've attached mapping tables for the six fonts.  The encoding is not as consistent as I would have expected.  In 4 cases the pft and yaff files contain 2 internal fonts, fortunately, the encoding appears to be the same for both. In these cases, however, the corresponding -map.txt file has the encoding of the 2nd font following the encoding of the 1st font (though redundant).

In other cases, encoding may be the same but the starting index is different: `0x00`, `0x01`, or `0x21`.  Some ASCII punctuation, like`-` , `=` , or `+` will change position or will be missing ("empty" appears in the first column if a glyph is absent). The Ethiopic part is consistent for the most part.

Another note, is that in the address range (generally) 0xd4 - 0xe7, there is an "X" in the first column.  These symbols were decomposed diacritical marks, which was a trick used to work with the 320+ Ethiopic symbols within the confines of what 8 bit space would allow.  Unicode uses a fully composed character model for Ethiopic, so there are no correspondences for the standalone diacritical marks.  Therefore, I assigned them to the start of Unicode's Private Use Area (for lack of a better idea).

I can adjust the files as advised, the `amrq1103` and `amsq1103` have fully identical encodings and likewise the map files turned out the same.


[amsq1103-map.txt](https://github.com/robhagemans/monobit/files/11057495/amsq1103-map.txt)
[amhs1011-map.txt](https://github.com/robhagemans/monobit/files/11057496/amhs1011-map.txt)
[amrq1103-map.txt](https://github.com/robhagemans/monobit/files/11057497/amrq1103-map.txt)
[amrl1103-map.txt](https://github.com/robhagemans/monobit/files/11057498/amrl1103-map.txt)
[amds1103-map.txt](https://github.com/robhagemans/monobit/files/11057499/amds1103-map.txt)
[amdl1103-map.txt](https://github.com/robhagemans/monobit/files/11057500/amdl1103-map.txt)

**Comment by robhagemans** [comment]
Thanks, that's great!

It might be possible to condense all of these into one 'code page' - for example where a glyph is empty in the font, the converter should not normally label it anyway. Likewise where the starting index is different that's probably a decoding error - sorry I had not spotted that. There are multiple slightly different versions of the format and I have not fully understood all fields in the header, there may be a field saying effectively 'add 32 to the codepoint'. In any case I can easily re-extract them with a shifted index, then apply a common code page.

It's surprising that Unicode doesn't have entries for the diacritics, I thought one of the principles was to encode separate glyphs if they had been separately encoded prior to Unicode, so as to allow round-trip conversion of old text files. I wonder if there's a case to be made to the Unicode Consortium to get them added, given that clearly they *were* encoded separately in the past?

One thing that could be additionally useful is to define names (in Latin script) for the diacritics missing from Unicode, so that people know which glyph is meant - whether or not we use the private use area. Unless the symbols don't really have an accepted standalone name in which case it wouldn't really help anyone...

There's no need to update the `.yaff` files for now, once I've implemented the code page I can easily re-extract and share the updated files (which might then need checking for any further bugs)

Thanks again
Rob

**Comment by robhagemans** [comment]
Hi @dyacob, I've used your maps to label the yaff files, attaching here: [dashen-labelled.zip](https://github.com/robhagemans/monobit/files/11066481/dashen-labelled.zip)

It seems to me `amsq1103-map.txt` applies cleanly to four fonts: `amsq`, `amrq`, `amrl` and `amds`. Some of these miss glyphs compared to `amsq` but that's fine. I didn't see a `-` in the place of `=`, I wonder if that was just a missing glyph? (Note that the `yaff` format records an empty raster as `-`). I hope I haven't overlooked anything, it's difficult even to just compare glyph shapes in a script I'm unfamiliar with.

My hunch on the other two `amhs` and `amdl` was wrong, they have a truly different encoding. I applied your maps to them. 

I'd like to include your `amsq` map  as "the" Dashen character map with `monobit` (I'll credit you as the author of the mapping, of course). It's the most common - the other two only apply to a single font each. Let me know what you think.

**Comment by dyacob** [comment]
I've attached what I think is likely the cannonical mapping where I've added servicable names for the diacritical marks.  There is a bit of guess work and a number of them I simply don't recognize and haven't seen in other fonts that took this approach.  I'll try to get some more information from the Dashen author over the weekend.

Where the mappings are slightly different in a few of the fonts for punctuation, is not critical in my mind.  They can be reshuffled post-conversion. The desire from a conversion would be to recover the Ethiopic glyphs, the Latin glyphs are 
 nice to have, but a much smaller concern. 

A note on amrl1103.yaff file, the glyph at 0x3b (ጮ, U+132E) is missing, though it is present in every other file.  Could you check if this might be a conversion error?  Possibly it truly is missing.

On the subject of the diacritics, they really are artificial elements that don't fit the conceptual model in culture. Up until the typewriter, the letters were always whole, which is also how they are taught. During 1992-3 the Unicode Consortium did review adopting a diacritic based approach at length with stakeholders, and the concensus was that they really have no place in the standard, they best left behind.  

[dashen-map.txt](https://github.com/robhagemans/monobit/files/11066440/dashen-map.txt)

**Comment by dyacob** [comment]
Our messages seem to have crossed :-)  It is absolutely OK to include the `amsq` file, or the one from my previous message.  Anything that I post here is quite alright to include when it makes sense.

Regarding the punctuation changes, the 39th glyph in the various files as I observe them:

`=` , amrl1103, amrq1103, amsq1103 (0x47)
`-` , amdl1103  (0x2b)
`+` , amhs1011 (0x26)
_empty_, amds1103 (0x47)

**Comment by robhagemans** [comment]
Thanks for the punctuation summary, that makes sense - it's consistent with the interpretation that `amdl` and `amhs` have their own different character maps and the other four are realisations of the same character map, though not all complete.

As to `amrl`, as far as I can see there really is no glyph at `0x3b`. The codepoint is defined in the font but its bitmap is empty. It's not so easy to see from the binary as this font has fairly large bitmaps and they are stored as 8-pixel slices; however the glyph is missing from both the "Dashen" and the "PCL" font, which are stored in completely different formats, so it would be rather a coincidence for them to drop out of both. Moreover, it's neither the first nor the last codepoint and the code reads all the bytes in the file consecutively, so if there were a bug the glyph would appear in some form in the previous or next bitmap, and that doesn't seem to be the case.

**Comment by dyacob** [comment]
Thanks @robhagemans for looking into it and the explanation 😊.  I was able to speak to the Dashen creator over the weekend and he has since sent me some code charts.  They don't add much insight though to disambiguate the diacritical marks / letter components. I've been tied up but expect to be able to go through the materials by Thursday.

**Comment by robhagemans** [comment]
I'm closing this issue - @dyacob, if more information surfaces on the format or encoding, please feel free to reopen.

**Comment by dyacob** [comment]
Hi @robhagemans , I was actually working on it last evening, can you contact me offline please at yacob <at> geez.org? thanks!

**Comment by dyacob** [comment]
This update takes the dashen-map.txt file that is in the `topic-bugfixes` branch and replaces lines 152-171 with new symbol names based on their input sequences.  There are are two "leftover" marks whose names were match a counterpart with `_2` appended.

[dashen-map.txt](https://github.com/robhagemans/monobit/files/11237344/dashen-map.txt)

**Comment by robhagemans** [comment]
This has been merged, thanks!
