### ISSUE TITLE
All Draw Font Not Working

### ISSUE THREAD

**Issue by cheznewa** [robhagemans/monobit#19]
The YAFF Working But DRAW Not Working For The Majoritary, But A Tiny Pretty Working.
A Error Out Is :::: `ERROR: tuple.index(x): x not in tuple`

You Can Fix It?

with python 3.9 on cygwin.

**Comment by robhagemans** [comment]
Please provide  enough information to reproduce the problem - I would need the `draw` file where the problem occurs and the command you're giving, without it there i no way I can find out what went wrong for you. Also, what version of monobit are you using?

**Comment by cheznewa** [comment]
I use the last version (with a git clone ...) and i you say for example the `SAA5050.draw` return me `ERROR: tuple.index(x): x not in tuple` with banner and convert

But `Datapoint-8600.draw` Is Working.

**Comment by robhagemans** [comment]
Thanks! I can reproduce the issue. The files which are not working have an extra newline between the label and the glyph definition, and after some change at some point the converter can't deal with that anymore. I should be able to fix that.

Thanks for taking the time to report the problem.

**Comment by cheznewa** [comment]
```
.@@@@@.@..................@..........@...@...............@..
...@...@..................@..........@...@...............@..
...@...@@@@...@@@..@@@@...@..@........@.@...@@@..@...@...@..
...@...@...@.....@.@...@..@.@..........@...@...@.@...@...@..
...@...@...@..@@@@.@...@..@@...........@...@...@.@...@...@..
...@...@...@.@...@.@...@..@.@..........@...@...@.@...@......
...@...@...@..@@@@.@...@..@..@.........@....@@@...@@@@...@..
............................................................
............................................................

```

It's Working!

**Comment by robhagemans** [comment]
Great!
