### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by cheznewa** [robhagemans/monobit#21]
1. More than one enter in texte make error is `ERROR: tuple index out of range` before do not make this error.
2. The VT52.yaff i dont know why he me superpose double chars by double chars? Always to insert Space Per Chars.
3. Some code ANSI no working for example the character 0x85 make error is `ERROR: tuple index out of range` in the VT100.yaff and 0x83 make error is `ERROR: min() arg is an empty sequence`.

**Comment by robhagemans** [comment]
Thanks @cheznewa for the details. I could reproduce the issue and have fixed it.

**Comment by cheznewa** [comment]
a another bug for cmsy*.pk
source ::::: https://www.ctan.org/tex-archive/fonts/cm/pk
./monobit/banner.py -f pk120/cmsy10.120pk S
return me :::
WARNING: Raster data truncated.
ERROR: cannot fit 'int' into an index-sized integer

**Comment by cheznewa** [comment]
all bug fixed but one bug left.
and the code 0x85 do not show.

**Comment by cheznewa** [comment]
okay but you can fix the last bug of the pk format?

**Comment by cheznewa** [comment]
All Done!

**Comment by cheznewa** [comment]
is planned to render/convert a full font from ttf/otf with the size define?

**Comment by robhagemans** [comment]
No, I'm not going to implement a rasteriser for outline fonts. That is a
specialist and complex topic, I would recommend using a standard dictionary
such as Freetype
