### ISSUE TITLE
Padding fefaulting to 1

### ISSUE THREAD

**Issue by jahu00** [robhagemans/monobit#25]
When converting FON file to PNG I've noticed that it has 1px padding around each character (except for the outer edge of the image). while searching how to set padding in help, I've noticed that it says that it should actually default to 0. After explicitly setting padding to 0, the resulting image was as expected. Either the help is wrong or padding does not default to 0.

**Comment by robhagemans** [comment]
Hi, the help is wrong, thanks for reporting! 
Default padding of 1 pixel is intentional. I'll update the help.

**Comment by robhagemans** [comment]
Fixed, will be in next release update

**Comment by vbgfhfngfdtyreyt** [comment]
My apologies, what exactly is the syntax for removing the padding? I don't see it in --help.

**Comment by robhagemans** [comment]
`monobit-convert inputfont to output.png -padding=0x0`

see `monobit-convert --help save -format=image` for other options for image output
