### ISSUE TITLE
I Cant Change Color Paper And Ink As Image

### ISSUE THREAD

**Issue by cheznewa** [robhagemans/monobit#27]
Hello/Hi Again A Bug Where I Cant Change Color As Image So Before I Can Change The Color
And The Default Color Writed Is False So What Color Default?

Im Tired You Regressing This Program Stop It!

**Comment by robhagemans** [comment]
> 
> Im Tired You Regressing This Program Stop It!

I apologise for tiring you out by providing a piece of code that's in version 0.x for free by putting in my time. I did not realise that by doing so I was wasting @cheznewa's precious time. 

This code is in version 0.x meaning it is not yet stable. i will be making further breaking changes, regardless of how this affects @cheznewa's life. if you are unhappy about how it works or is developed, I invite you to write your own, as all previous states are available for free for you to use through Github.  You could even take the state of this code base as it was before I so wantonly started regressing it  and keep using it in your busy life.
