### ISSUE TITLE
Document .yaff in fileformats.archiveteam.org wiki

### ISSUE THREAD

**Issue by clemtre** [robhagemans/monobit#29]
Hi, I have stumbled upon http://fileformats.archiveteam.org, from its FAQ :

> The purpose of this wiki is to "Solve the File Format Problem".

>The File Format Problem in this context is that over the last century, many types of electronic information have been presented in formats that are non-intuitive and subject to the rapidly-shifting interests of what is newest and best. As a result, thousands of programs, documents, images and binary files are in danger of being unreadable to later generations as no readily available information about accessing them is to be found. Various projects have been launched in the last 20 years to deal with this problem, but they all lack a groundswell of directed volunteers working to once and for all get all the disparate information into one place and easily referenced by all. This is the goal of this project.

>The project started on November 1st, 2012. All are invited to register and contribute. The goal is to have a massive bulk of knowledge in one place for all to use and incorporate into other similar directories and sites, providing a needed resource for generations to come. 

I have seen .bdf and .hex formats listed, but not .yaff. Do you think of this format being relevant enough to be written in the wiki as an interface format for bitmap fonts ?

**Comment by robhagemans** [comment]
For now I'd say it's better not to - the format is not yet stable 1.0 so it could be confusing to separately document this at the wiki. Adding a link to the definition on this site wouldn't be a problem of course
