### ISSUE TITLE
Not an issue, maybe a feature request?   Single character conversion?

### ISSUE THREAD

**Issue by ClaireCJS** [robhagemans/monobit#30]
Hi,

It seems like this tool has the potential to maybe help me out?

I'm looking to convert the devil face emoji to the sixel representation described here:
https://vt100.net/dec/vt320/soft_characters

So basically:

How do I convert the devil face emoji (or any emoji) into a sequence like this: 
ESC P 1;1;1;0;0;2;0;0 { P ???owYn||~ywo?? / ?IRJaVNn^NVbJRI ESC \ [etc etc]}

It's the decoding to sixel that I don't really want to do by hand....

**Comment by robhagemans** [comment]
Monobit supports DEC DRCS soft fonts (format `dec`), does that do what you are looking for?

**Comment by robhagemans** [comment]
As far as I can see this is already implemented as format `dec`, if anything is missing please feel free to reopen or raise a new issue.
