### ISSUE TITLE
Looking for documentation on the use of subset

### ISSUE THREAD

**Issue by TomKeddie** [robhagemans/monobit#38]
Hi, I'm trying to extra a subset of characters from a font.  I'm using MS_Sans_Serif_18.yaff from the collection in one of your other repos.  I've dug into the source and tried a lot of things but I can't figure out the syntax to specific a subset.

As the font loads I added a print statement to print the labels and I see what looks like good data.
```
('u+0020', '0x20')
('u+0021', '0x21')
.
.
.
('u+00fe', '0xfe')
('u+00ff', '0xff')
```
I can't work out the syntax to specify this as a subset on the command line.  I've tried lots of things for over an hour, I think it would be great to see some examples in the --help or README.  I can see in the tests you do things like range(12) but I can't work out how this would look on the command line.

I've tried
```
monobit-convert MS_Sans_Serif_18.yaff subset -chars='A'
monobit-convert MS_Sans_Serif_18.yaff subset -labels=0xff
monobit-convert MS_Sans_Serif_18.yaff subset -labels='u+0xff'
```
and lots of similar things but I get no fonts.  I can see in the subset method in font.py that what I'm supplying is returning an empty set so I'm clearing not getting the syntax right.  Hoping you can add some examples to either --help or to the README.

I know I can hack the yaff file but I'd prefer to be able to trace my steps when I come back to this process.  Thanks.

**Comment by robhagemans** [comment]
Hi @TomKeddie , the following examples are expected to work - I double checked them on my machine:
```
monobit-convert MS_Sans_Serif_18.yaff subset -labels=0xff 
monobit-convert MS_Sans_Serif_18.yaff subset -labels=u+00ff
monobit-convert MS_Sans_Serif_18.yaff subset -codepoints=0xff
# single character
monobit-convert MS_Sans_Serif_18.yaff subset -chars=ÿ
# list of characters
monobit-convert MS_Sans_Serif_18.yaff subset -chars=A,Z
# range of characters
monobit-convert MS_Sans_Serif_18.yaff subset -chars=A-Z
```

Let me know if these still cause issues - I only test on Linux, I don't expect issues with these on other systems but with command lines there can be subtleties.

The documentation is indeed poor, unfortunately. Someday I'll find some time to write more of it...

**Comment by TomKeddie** [comment]
Thanks, I reinstalled and your examples are working for me.  We can consider this issue documentation ;-)
