### ISSUE TITLE
Atari Font support

### ISSUE THREAD

**Issue by th-otto** [robhagemans/monobit#4]
Not really an issue, but if you ever look into supporting Atari (GEM) bitmap fonts again. you may want to look at https://github.com/th-otto/gemfedit/blob/master/tools/fntconv.c. That repo also has the 6x6 system font (system08.fnt, was used for small icon lables) and the 16x32 system font (system20.fnt, only present in TT machines). And of course, that tool uses its own text-based format ;)

**Comment by robhagemans** [comment]
Hi, thanks for the link!

**Comment by robhagemans** [comment]
Hi @th-otto, thanks again for the link to your repo. I had another look at Atari formats and did a base implementation of a GDOS font format reader, mostly based on the documentation in the Atari compendium and on John Elliott's site http://www.seasip.info/Gem/filefmt.html .I noticed some GEM fonts have compressed bitmaps which neither of these sources discuss. In your repo I saw you had added a decoding algorithm - did you find any documentation for the compression format, or is this perhaps based on GEM sources or reverse-engineered from scratch?

**Comment by th-otto** [comment]
Uh, its been a long time since i implemented this. IIRC, it was taken from some PC-GEM sources. I also never saw any GDOS fonts in compressed format for Atari, only for PC-GEM. However the fontviewer is able to display the compressed fonts i could find.

**Comment by robhagemans** [comment]
Thanks for the fast reply! From your code, I gather it's a form of run length encoding of the leading zeros in a field of varying bit width, followed by the remaining pixels uncompressed. I guess I should be able to make that work...

**Comment by robhagemans** [comment]
Actually, loooks like this is a description of the scheme: https://github.com/shanecoughlan/OpenGEM/blob/master/source/OpenGEM-7-RC1-SDK/OpenGEM-7-SDK/GEM%20VDI%20AND%20SOURCE%20CODE/GEM%203%20VDI%20source%20code/DECODE.A86#L50
