### ISSUE TITLE
BDF export does not work

### ISSUE THREAD

**Issue by trevorld** [robhagemans/monobit#6]
I'm observing that conversion to the `bdf` format currently does not work.  Here is a minimal, reproducible example:

```
$ wget https://github.com/fcambus/spleen/raw/master/spleen-6x12.bdf &> /dev/null
$ python3 convert.py spleen-6x12.bdf spleen.yaff &> /dev/null
$ python3 convert.py spleen.yaff spleen.bdf
ERROR: 'get-ordinal'
```

The error is thrown at line 478 of `bdf.py`:

            xlfd_props['DEFAULT_CHAR'] = font.get_ordinal(font.default_char)

Note the `Font` class defined in `font.py` does not define a `get_ordinal()` method but I'm not sure how to fix it.

**Comment by robhagemans** [comment]
Hi, I've pushed a fix for this issue, note that there are still much wider unfixed problems but the BDF conversion works again.

**Comment by trevorld** [comment]
Thanks!
